# Site settings
lang: en
title: Vedic Documentation
description: The documentation for Vedic, world first programming language in sanskrit.
url: https://vedic-lang.github.io # the base hostname & protocol for your site
twitter_username: ptprashant09
author: Pt. Prashant Tripathi
github_username: vedic-lang
keywords: vedic, vedic,script, programming language, sanskrit, ptprashanttripathi, Pt. Prashant Tripathi
google-site-verification: _Ehwbp1SdA9Ki8l2ZPlKzPqCJmMFZC6TZDFbYKgTctk
meta:
  keywords: vedic, vedic,script, programming language, sanskrit, ptprashanttripathi, Pt. Prashant Tripathi
  author: Pt. Prashant Tripathi
  google-site-verification: _Ehwbp1SdA9Ki8l2ZPlKzPqCJmMFZC6TZDFbYKgTctk
google:
  gtag: GTM-TLXXSMK
readme_index:
  with_frontmatter: true
